### ISSUE TITLE
grouped code generation in the end of file maybe has a problem

### ISSUE THREAD

**Issue by bravelincy** [retyui/group-css-media-queries-loader#3]
I using `stylus` in my project, so that media-query can be nested, the scenario is:
``` css
bg2x(src) {
  @media screen and (min-resolution: 2dppx) {
    background-image: url(src);
  }
}

.foo {
  ...
  bg2x("img/foo@2x.png");
}

@media screen and (max-width: 768px) {
  .foo {
    bg2x("img/foo_small@2x.png");
  }
}
```
finally compiled:
``` css
@media screen and (max-width: 768px) and (min-resolution: 2dppx) {
 foo {
    bg2x("img/foo_small@2x.png");
  }
}

@media screen and (min-resolution: 2dppx) {
  ...

  .foo {
    ...
    bg2x("img/foo@2x.png");
  }
}
```

the result is `.foo` doesn't use `foo_small@2x.png` but `img/foo@2x.png`
